export const black: string;
export const danger: string;
export const facebook: string;
export const google: string;
export const linkedin: string;
export const primary: string;
export const secondary: string;
export const tertiary: string;
export const white: string;
